name: Validate and stage release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to publish
        required: true
      publish_github:
        description: 'Create draft GitHub release'
        default: true
        type: boolean
      #publish_maven:
      #  description: 'Create Maven bundle'
      #  default: true
      #  type: boolean
      skip_validation:
        description: 'Skip version validations'
        default: false
        type: boolean

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
      - name: Setup Git and GitHub CLI
        run: |
          gh auth setup-git
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Validate version number
        if: ${{ ! inputs.skip_validation }}
        run: |
          [ "${{ inputs.version }}" == "$(cat pom.xml | grep '<version>' | tr -d '<>/[:alpha:][:space:]')" ] || (>&2 echo "Version does not match value in pom.xml"; exit -1)
      - name: Build artifact
        run: mvn package
      #- name: Sign Maven artifacts and create bundle
      #  if: ${{ inputs.publish_maven }}
      #  run: |
      #    echo -n "${GPG_SIGNING_KEY}" | base64 --decode | gpg --import
      #    
      #    pushd maven
      #    gpg -ab ${BUILD_NAME}-${BUILD_VERSION}.pom
      #    gpg -ab ${BUILD_NAME}-${BUILD_VERSION}.jar
      #    gpg -ab ${BUILD_NAME}-${BUILD_VERSION}-sources.jar
      #    gpg -ab ${BUILD_NAME}-${BUILD_VERSION}-javadoc.jar
      #    
      #    jar -cvf ${BUILD_NAME}-${BUILD_VERSION}-bundle.jar *
      #  env:
      #    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      #- name: Upload Maven bundle
      #  if: ${{ inputs.publish_maven }}
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Maven bundle
      #    path: maven/*-bundle.jar
      - name: Stage GitHub release
        if: ${{ inputs.publish_github }}
        run: |
          gh release create "v${{ inputs.version }}" --draft --title "Version ${{ inputs.version }}" target/gd-1.0.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release artifacts
          path: target/gd-1.0.0.jar
